---
abstract: 'Suddenly death (突然の死) generator'
author:
  - 'papix <mail@papix.net>'
build_requires:
  Encode: 2.39
  Test::More: 0.98
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-SuddenlyDeath
no_index:
  directory:
    - inc
provides:
  Acme::SuddenlyDeath:
    file: lib/Acme/SuddenlyDeath.pm
    version: 0.04
requires:
  Text::VisualWidth: 0.02
  base: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
